apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  user.conf: |
    [storage_policy]
    hot_volume = '/var/lib/clickhouse/hot'
    cold_volume = '/var/lib/clickhouse/cold'
    move_factor = 0.2
