apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
spec:
  resources:
    requests:
      storage: 15Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: clickhouse-storage
